import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Command,
  Copy,
  CreditCard,
  Facebook,
  File,
  FileText,
  Globe,
  HelpCircle,
  Image,
  Info,
  Laptop,
  Linkedin,
  Loader2,
  LucideProps,
  MapPin,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Share2,
  SunMedium,
  Tag,
  Ticket,
  Trash,
  Twitter,
  User,
  Users,
  X,
  Calendar,
  Clock,
  Music,
  Heart,
  Menu,
  Home,
  LogOut,
  Mail,
  LogIn,
  Shield,
  Eye,
  Edit,
  Upload,
  Video,
  Save,
  Play,
  Pause,
  AlertCircle,
  type Icon as LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  calendar: Calendar,
  mapPin: MapPin,
  clock: Clock,
  ticket: Ticket,
  music: Music,
  users: Users,
  heart: Heart,
  menu: Menu,
  home: Home,
  logOut: LogOut,
  check: Check,
  mail: Mail,
  info: Info,
  logIn: LogIn,
  shield: Shield,
  fileText: FileText,
  eye: Eye,
  edit: Edit,
  upload: Upload,
  video: Video,
  save: Save,
  play: Play,
  alertCircle: AlertCircle,
  share: Share2,
  copy: Copy,
  facebook: Facebook,
  twitter: Twitter,
  linkedin: Linkedin,
  tag: Tag,
  globe: Globe,
  pause: Pause,
}